routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () 
{
    /** Serviços */
    Route::resource('/services', 'Admin\ServiceController');
    /** Agendamentos */
    Route::resource('/agendamentos', 'Admin\AgendamentoController');

});

app/Models/Agendamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Agendamento extends Model
{
    public $timestamps = false;

    protected $guarded = [];
}

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    public $timestamps = false;

    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AgendamentoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Agendamento;
use Illuminate\Http\Request;

class AgendamentoController extends Controller
{
    private $model;

    public function __construct(Agendamento $model)
    {
        $this->model = $model;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agendamentos = $this->model->paginate();
        return view('admin.agendamentos.index',compact('agendamentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.agendamentos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=> 'required',
        ]);

        $data = $request->all();
        Agendamento::create($data);

        return redirect()->route('agendamentos.index')->with('message','Agendamento Inserido!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agendamento = $this->model->find($id);
        return view('admin.agendamentos.edit',compact('agendamento'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'=> 'required',
        ]);

        $data = $request->all();
        $agendamento = Agendamento::find($id);
        $agendamento->update($data);
        
        return redirect()->route('agendamentos.index')->with('message','Agendamento Atualizado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $agendamento = $this->model->find($id)->delete();
        return redirect()->route('agendamentos.index')->with('message','Agendamento Deletado!');
    }
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Service;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    private $model;

    public function __construct(Service $model)
    {
        $this->model = $model;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $service = Service::paginate();
        return view('users.services.index',compact('service'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'name'=> 'required',
        // ]);

        $data = $request->all();
        $this->model->create($data);
        return redirect('service')->withStatus('Inserido com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = $this->model->find($id);
        return view('users.services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, [
        //     'name'=> 'required',
        // ]);

        $data = $request->all();
        $service = Service::find($id);

        $service->update($data);
        return redirect('services')->withStatus('Serviço atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->model->find($id)->delete();
        return redirect('services')->withStatus('Serviço deletado com sucesso');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/agendamentos/create.blade.php
@extends('adminlte::page')

@section('title', 'Agendamento')

@section('content_header')
    <h1>Cadastro de Agendamento</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('agendamentos.store') }}" method="POST">
                @csrf
                {{ method_field('POST') }}
                <div class="form-group col-md-5">
                    <label>Serviço</label>
                    <select class="form-control" name="service" required>
                        <option value="">Selecione um serviço</option>
                        @foreach (App\Models\Service::all() as $item)
                            <option value="{{ $item->name }}">{{ $item->name }}</option>
                        @endforeach
                    </select>
                    @error('service')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Data/Horário</label>
                    <input type="datetime" name="dt_agendamento" class="form-control @error('dt_agendamento') is-invalid @enderror" required>
                    @error('dt_agendamento')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Cliente</label>
                    <input type="text" name="cliente" class="form-control @error('cliente') is-invalid @enderror" required>
                    @error('cliente')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Raça</label>
                    <input type="text" name="raca" class="form-control @error('raca') is-invalid @enderror" required>
                    @error('raca')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                   <button type="submit" class="btn btn-dark">Atualizar</button>
                </div>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/admin/agendamentos/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar Agendamento do Cliente:<b>{{ $agendamento->cliente }}</b></h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('agendamentos.update', [$agendamento->id]) }}" method="POST">
                @csrf
                {{ method_field('PATCH') }}
                <div class="form-group col-md-8">
                    <label>Serviço</label>
                    <select name="company_id" id="" class="form-control">
                        @foreach (App\Models\Service::all() as $service)
                            <option value="{{ $service->id }}"
                                @if ($agendamento->service == $service->name) selected @endif
                                >{{ $service->name }}</option>
                        @endforeach
                    </select>
                    @error('service')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Data/Horário</label>
                    <input type="datetime" name="dt_agendamento" class="form-control @error('dt_agendamento') is-invalid @enderror"
                        value="{{ $agendamento->dt_agendamento }}">
                    @error('dt_agendamento')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Cliente</label>
                    <input type="text" name="cliente" class="form-control @error('cliente') is-invalid @enderror"
                        value="{{ $agendamento->cliente }}">
                    @error('cliente')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group col-md-5">
                    <label>Raça</label>
                    <input type="text" name="raca" class="form-control @error('raca') is-invalid @enderror"
                        value="{{ $agendamento->raca }}">
                    @error('raca')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                   <button type="submit" class="btn btn-dark">Atualizar</button>
                </div>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/admin/agendamentos/index.blade.php
@extends('adminlte::page')

@section('title', 'Agendamentos')

@section('content_header')
      <h1>Agendamentos</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        Todos os agendamentos
                    </li>
                </ol>
            </nav>
            @if (Session::has('message'))
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5>
                        {{ Session::get('message') }}
                </div>
            @endif
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    @if (count($agendamentos) > 0)
                        <tr>
                            <th>Dt. Agendamento</th>
                            <th>Cliente</th>
                            <th>Raça</th>
                            <th style="width: 40px">Ações</th>
                        </tr>
                    @else
                        <td>Nenhum agendamento cadastrado</td>
                    @endif
                </thead>
                <tbody>
                    @foreach ($agendamentos as $agendamento)
                        <tr>
                            <td>{{ $agendamento->dt_agendamento }}</td>
                            <td>{{ $agendamento->cliente ?? 'S/N' }}</td>
                            <td>{{ $agendamento->raca ?? 'S/N' }}</td>
                            <td>
                                <div class="btn-agendamento btn-sm">
                                    <a href="{{ route('agendamentos.edit', [$agendamento->id]) }}" class="btn btn-warning"><i
                                        class="fas fa-edit"></i></a>

                                    <a href="#" class="btn btn-danger"
                                        data-toggle="modal" data-target="#modal-danger{{ $agendamento->id }}">
                                        <i class="fas fa-trash"></i></a>

                                    <div class="modal fade" id="modal-danger{{ $agendamento->id }}">
                                        <div class="modal-dialog">
                                            <form action="{{ route('agendamentos.destroy', [$agendamento->id]) }}" method="POST">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <div class="modal-content bg-danger">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title">Atenção</h4>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Deseja realmente exluir  o agendamento do dia <b>{{ $agendamento->dt_agendamento }}</b> ?</p>
                                                    </div>
                                                    <div class="modal-footer justify-content-between">
                                                        <button type="submit" class="btn btn-outline-light"
                                                            data-dismiss="modal">Cancelar</button>
                                                        <button type="submit"
                                                            class="btn btn-outline-light">Excluir</button>
                                                    </div>
                                                </div>
                                            </form>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>
                                    @endif
                                    <!-- /.modal -->
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/admin/services/create.blade.php
@extends('adminlte::page')

@section('title', 'Serviço')

@section('content_header')
    <h1>Serviços</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
           
        </div>
        <div class="card-body">
            <form action="{{ route('services.store') }}" method="POST">
                @csrf
                {{ method_field('POST') }}
                <div class="form-service col-md-5">
                    <label>Tipo de Serviço</label>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                        value="{{ $service->name }}" required>
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service col-md-5">
                    <label>Preço</label>
                    <input type="text" name="preco" class="form-control @error('preco') is-invalid @enderror"
                    placeholder="Descrição" value="{{ $service->preco }}" required>
                    @error('preco')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service col-md-5">
                    <label>Data de Disponibilidade</label>
                    <input type="text" name="dt_disponivel" class="form-control @error('dt_disponivel') is-invalid @enderror"
                    placeholder="Descrição" value="{{ $service->dt_disponivel }}" required>
                    @error('dt_disponivel')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service">
                   <button type="submit" class="btn btn-dark">Atualizar</button>
                </div>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/admin/services/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar Serviço -  <b>{{ $service->name }}</b></h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
           
        </div>
        <div class="card-body">
            <form action="{{ route('services.update', [$service->id]) }}" method="POST">
                @csrf
                {{ method_field('PATCH') }}
                <div class="form-service col-md-5">
                    <label>Tipo de Serviço</label>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                        value="{{ $service->name }}">
                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service col-md-5">
                    <label>Preço</label>
                    <input type="text" name="preco" class="form-control @error('preco') is-invalid @enderror"
                    placeholder="Descrição" value="{{ $service->preco }}">
                    @error('preco')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service col-md-5">
                    <label>Data de Disponibilidade</label>
                    <input type="text" name="dt_disponivel" class="form-control @error('dt_disponivel') is-invalid @enderror"
                    placeholder="Descrição" value="{{ $service->dt_disponivel }}">
                    @error('dt_disponivel')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-service">
                   <button type="submit" class="btn btn-dark">Atualizar</button>
                </div>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/admin/services/index.blade.php
@extends('adminlte::page')

@section('title', 'Serviços')

@section('content_header')
      <h1>Serviços</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        Todos os serviços
                    </li>
                </ol>
            </nav>
            @if (Session::has('message'))
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5>
                        {{ Session::get('message') }}
                </div>
            @endif
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    @if (count($services) > 0)
                        <tr>
                            <th>Nome</th>
                            <th>Preço</th>
                            <th>Data de disponibilidade</th>
                            <th style="width: 40px">Ações</th>
                        </tr>
                    @else
                        <td>Nenhum serviço cadastrado</td>
                    @endif
                </thead>
                <tbody>

                        @foreach ($services as $service)
                            <tr>
                                <td>{{ $service->name }}</td>
                                <td>{{ $service->preco }}</td>
                                <td>{{ $service->dt_disponivel ?? 'S/N' }}</td>
                                <td>
                                    <div class="btn-service btn-sm">

                                        <a href="{{ route('services.edit', [$service->id]) }}" class="btn btn-warning"><i
                                            class="fas fa-edit"></i></a>

                                        <a href="#" class="btn btn-danger"
                                            data-toggle="modal" data-target="#modal-danger{{ $service->id }}">
                                            <i class="fas fa-trash"></i></a>

                                        <div class="modal fade" id="modal-danger{{ $service->id }}">
                                            <div class="modal-dialog">
                                                <form action="{{ route('services.destroy', [$service->id]) }}" method="POST">
                                                    @csrf
                                                    {{ method_field('DELETE') }}

                                                    <div class="modal-content bg-danger">
                                                        <div class="modal-header">
                                                            <h4 class="modal-title">Atenção</h4>
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>Deseja realmente exluir  o serviço <b>{{ $service->name }}</b> ?</p>
                                                        </div>
                                                        <div class="modal-footer justify-content-between">
                                                            <button type="submit" class="btn btn-outline-light"
                                                                data-dismiss="modal">Cancelar</button>
                                                            <button type="submit"
                                                                class="btn btn-outline-light">Excluir</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </div>
                                        @endif
                                        <!-- /.modal -->

                                    </div>
                                </td>
                            </tr>
                        @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer"></div>
    </div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection